---
name: Run Importer for Markdowns

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.md"

permissions: {}

jobs:
  importer:
    name: Run Importer Generate for Markdowns
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3
        with:
          go-version: ">=1.18.0"
          check-latest: true

      - name: Install Importer
        run: go install github.com/upsidr/importer/cmd/importer@v0.1.4

      - name: Run Importer against all *.md files
        run: find . -name '*.md' -exec importer update {} \;
      - name: Check if any change compared to the branch HEAD
        run: |
          git status --short
          git diff-index --quiet HEAD
